## Put comments here that give an overall description of what your
## functions do

## In a similar way of cacheVector, makeCacheMatrix calculate and preserve the 
## value of the inverse matrix sended by cacheSolve function. This one valides
## that the cache variable stored in getinversematrix in the list generated by 
## makeCacheMatrix is empty or not. If this is empty then get the value of the 
## matrix stored in get into the list and calculate the inverse.


## Write a short comment describing this function
## Defines a function that create a list with the results of 4 functions that
## manage the state of cache using variables out of local environment. 
## In the first time the cache is set to NULL.  

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinversematrix <- function(solve) m <<- solve
  getinversematrix <- function() m
  list(set = set, get = get,
       setinversematrix = setinversematrix,
       getinversematrix = getinversematrix)
}



## Write a short comment describing this function
## This function reads the content of the "getinversematrix" position of the list 
## generated by makeCacheMatrix. If it is not NULL then print the content. If 
## it is null then recover the matrix from "get" position, calculates the inverse,
## set the value of the cache variable in the list and print the inverse

cacheSolve <- function(x, ...) {
  m <- x$getinversematrix()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinversematrix(m)
  m
  ## Return a matrix that is the inverse of 'x'
}